Repository Potato-Miners/Team-Matching-FE-Web, pull requests merged in 2023-12, with the labels that each got.

#59 feature: mypage 신청 중인 팀 기능 구현
  team-matching-web/.pnp.cjs
  team-matching-web/.yarn/cache/@tanstack-query-devtools-npm-5.13.3-913e8f4969-baa65db5f2.zip
  team-matching-web/.yarn/cache/@tanstack-react-query-devtools-npm-5.13.3-d05d8115b8-754f3de815.zip
  team-matching-web/.yarn/install-state.gz
  team-matching-web/package.json
  team-matching-web/src/API/TeamMon.js
  team-matching-web/src/App.js
  team-matching-web/src/components/ApprovalModal/ApprovalModal.jsx
  team-matching-web/src/components/MyTeam/MyTeam.jsx
  team-matching-web/src/components/MyTeam/MyTeam.module.css
  team-matching-web/src/components/TeamAct/TeamAct.jsx
  team-matching-web/src/components/TeamItem/TeamItem.jsx
  team-matching-web/src/components/TeamItem/TeamItem.module.css
  team-matching-web/src/components/TeamJudging/TeamJudging.jsx
  team-matching-web/src/components/TeamJudging/TeamJudging.module.css
  team-matching-web/src/pages/MyPage/MyPage.jsx
  team-matching-web/yarn.lock
Labels: ✨Feature, ⚙Setting

#66 [refactor] #53 - 리팩토링
  team-matching-web/src/API/TeamMon.js
  team-matching-web/src/components/MyInfo/MyInfo.jsx
  team-matching-web/src/pages/Board/Board.jsx
  team-matching-web/src/pages/FindTeam/FindTeam.jsx
  team-matching-web/src/pages/PostDetail/PostDetail.jsx
Labels: ⛏Refactor

#67 [fix] #60 - 검색 시 입력될 때마다 cache 되는 현상 수정
  team-matching-web/.yarn/install-state.gz
  team-matching-web/src/hooks/useDebounce.jsx
  team-matching-web/src/index.js
  team-matching-web/src/pages/FindTeam/FindTeam.jsx
  team-matching-web/src/pages/FindTeam/FindTeam.module.css
Labels: ✨Feature
