Repository Potato-Miners/Team-Matching-FE-Web, pull requests merged in 2023-08, with the labels that each got.

#37 #36 - 팀 새로 만들기 페이지 구현
  team-matching-web/.yarn/install-state.gz
  team-matching-web/src/API/TeamMon.js
  team-matching-web/src/components/ui/RoundBtn/RoundBtn.jsx
  team-matching-web/src/index.css
  team-matching-web/src/index.js
  team-matching-web/src/pages/FindTeam/FindTeam.jsx
  team-matching-web/src/pages/NewPost/NewPost.jsx
  team-matching-web/src/pages/NewTeam/NewTeam.jsx
  team-matching-web/src/pages/NewTeam/NewTeam.module.css
Labels: ✨Feature

#39 feat: 헤더 드롭다운 메뉴 구현
  team-matching-web/.yarn/install-state.gz
  team-matching-web/src/components/Navbar/Navbar.jsx
  team-matching-web/src/components/Navbar/Navbar.module.css
  team-matching-web/src/components/SubMenu/SubMenu.jsx
  team-matching-web/src/components/SubMenu/SubMenu.module.css
Labels: ✨Feature, 🎨Design

#41 API: my info function
  team-matching-web/src/API/TeamMon.js
  team-matching-web/src/components/ChangeNickNameModal/ChangeNickNameModal.jsx
  team-matching-web/src/components/MyInfo/MyInfo.jsx
  team-matching-web/src/components/Navbar/Navbar.jsx
  team-matching-web/src/pages/Join/Join.jsx
Labels: 📫API

#43 #42 - 팀 가입 신청 기능 구현
  team-matching-web/src/components/ApplyModal/ApplyModal.jsx
  team-matching-web/src/components/ApplyModal/ApplyModal.module.css
  team-matching-web/src/pages/TeamDetail/TeamDetail.jsx
  team-matching-web/src/pages/TeamDetail/TeamDetail.module.css
Labels: ✨Feature

#44 #36 - 팀 새로 만들기 페이지 구현
  team-matching-web/.yarn/install-state.gz
  team-matching-web/src/API/TeamMon.js
  team-matching-web/src/pages/NewTeam/NewTeam.jsx
Labels: ✨Feature
