Repository Potato-Miners/Team-Matching-FE-Web, pull requests merged in 2023-07, with the labels that each got.

#15 #4 - Login 페이지 구현
  team-matching-web/src/App.js
  team-matching-web/src/components/Navbar/Navbar.jsx
  team-matching-web/src/components/Navbar/Navbar.module.css
  team-matching-web/src/index.js
  team-matching-web/src/pages/Join/Join.jsx
  team-matching-web/src/pages/Login/Login.jsx
  team-matching-web/src/pages/Login/Login.module.css
Labels: enhancement

#18 #6 - Post 페이지 구현
  team-matching-web/.yarn/install-state.gz
  team-matching-web/src/components/Navbar/Navbar.jsx
  team-matching-web/src/components/Post/Post.jsx
  team-matching-web/src/components/Post/Post.module.css
  team-matching-web/src/index.js
  team-matching-web/src/pages/Board/Board.jsx
  team-matching-web/src/pages/Board/Board.module.css
  team-matching-web/src/pages/Join/Join.jsx
  team-matching-web/src/pages/Login/Login.jsx
Labels: enhancement

#21 #17 - Post detail 페이지 구현
  team-matching-web/src/components/Post/Post.jsx
  team-matching-web/src/components/Post/Post.module.css
  team-matching-web/src/index.js
  team-matching-web/src/pages/Board/Board.jsx
  team-matching-web/src/pages/Board/Board.module.css
  team-matching-web/src/pages/Login/Login.module.css
  team-matching-web/src/pages/PostDetail/PostDetail.jsx
  team-matching-web/src/pages/PostDetail/PostDetail.module.css
Labels: enhancement

#22 #16 - 팀 찾기 페이지 구현
  team-matching-web/.pnp.cjs
  team-matching-web/.yarn/cache/classnames-npm-2.3.2-d2fdae468d-2c62199789.zip
  team-matching-web/.yarn/install-state.gz
  team-matching-web/package.json
  team-matching-web/src/components/Navbar/Navbar.jsx
  team-matching-web/src/components/TeamCard/TeamCard.jsx
  team-matching-web/src/components/TeamCard/TeamCard.module.css
  team-matching-web/src/index.css
  team-matching-web/src/index.js
  team-matching-web/src/pages/FindTeam/FindTeam.jsx
  team-matching-web/src/pages/FindTeam/FindTeam.module.css
  team-matching-web/src/pages/TeamDetail/TeamDetail.jsx
  team-matching-web/src/pages/TeamDetail/TeamDetail.module.css
  team-matching-web/yarn.lock
Labels: ✨Feature

#23 #20 - 마이페이지 구현
  team-matching-web/src/components/ChangeNickNameModal/ChangeNickNameModal.jsx
  team-matching-web/src/components/ChangeNickNameModal/ChangeNickNameModal.module.css
  team-matching-web/src/components/ChangePwModal/ChangePwModal.jsx
  team-matching-web/src/components/ChangePwModal/ChangePwModal.module.css
  team-matching-web/src/components/MyInfo/MyInfo.jsx
  team-matching-web/src/components/MyInfo/MyInfo.module.css
  team-matching-web/src/components/Navbar/Navbar.jsx
  team-matching-web/src/components/TeamAct/TeamAct.jsx
  team-matching-web/src/components/WriteComment/WriteComment.jsx
  team-matching-web/src/components/WriteComment/WriteComment.module.css
  team-matching-web/src/components/WritePost/WritePost.jsx
  team-matching-web/src/components/WritePost/WritePost.module.css
  team-matching-web/src/index.js
  team-matching-web/src/pages/Login/Login.module.css
  team-matching-web/src/pages/MyPage/MyPage.jsx
  team-matching-web/src/pages/MyPage/MyPage.module.css
Labels: ✨Feature

#24 fix: 팀 상세 페이지 re-rendering 현상 수정
  team-matching-web/src/pages/TeamDetail/TeamDetail.jsx
Labels: 🐞Bug

#27 design: footer 레이아웃 수정
  team-matching-web/src/App.css
  team-matching-web/src/App.js
  team-matching-web/src/components/Footer/Footer.module.css
  team-matching-web/src/index.css
  team-matching-web/src/pages/FindTeam/FindTeam.module.css
  team-matching-web/src/pages/Join/Join.module.css
  team-matching-web/src/pages/Main/Main.jsx
  team-matching-web/src/pages/Main/Main.module.css
  team-matching-web/src/pages/PostDetail/PostDetail.module.css
Labels: 🎨Design

#32 #30 - 게시판 글쓰기 페이지 구현
  team-matching-web/src/components/Navbar/Navbar.jsx
  team-matching-web/src/components/ui/Button/Button.jsx
  team-matching-web/src/components/ui/RoundBtn/RoundBtn.jsx
  team-matching-web/src/components/ui/RoundBtn/RoundBtn.module.css
  team-matching-web/src/index.css
  team-matching-web/src/index.js
  team-matching-web/src/pages/Board/Board.jsx
  team-matching-web/src/pages/NewPost/NewPost.jsx
  team-matching-web/src/pages/NewPost/NewPost.module.css
Labels: ✨Feature, 🎨Design

#33 api: login function
  team-matching-web/.pnp.cjs
  team-matching-web/.yarn/cache/hamt_plus-npm-1.0.2-67a52ee1df-af26ea32db.zip
  team-matching-web/.yarn/cache/recoil-npm-0.7.7-4452f58b67-65edecbcb8.zip
  team-matching-web/.yarn/cache/recoil-persist-npm-5.1.0-6c9c3d1452-03ee8417b9.zip
  team-matching-web/.yarn/install-state.gz
  team-matching-web/package.json
  team-matching-web/src/API/TeamMon.js
  team-matching-web/src/App.js
  team-matching-web/src/Recoil/state.js
  team-matching-web/src/components/Navbar/Navbar.jsx
  team-matching-web/src/pages/Join/Join.jsx
  team-matching-web/src/pages/Join/Join.module.css
  team-matching-web/src/pages/Login/Login.jsx
  team-matching-web/src/pages/Main/Main.jsx
  team-matching-web/yarn.lock
Labels: 📫API

#34 design: 전체 스타일링
  team-matching-web/src/components/Navbar/Navbar.jsx
  team-matching-web/src/components/Navbar/Navbar.module.css
  team-matching-web/src/components/TeamCard/TeamCard.module.css
  team-matching-web/src/index.css
  team-matching-web/src/pages/FindTeam/FindTeam.jsx
  team-matching-web/src/pages/FindTeam/FindTeam.module.css
  team-matching-web/src/pages/Join/Join.module.css
  team-matching-web/src/pages/Login/Login.module.css
  team-matching-web/src/pages/Main/Main.jsx
  team-matching-web/src/pages/Main/Main.module.css
  team-matching-web/src/pages/PostDetail/PostDetail.module.css
  team-matching-web/src/pages/TeamDetail/TeamDetail.module.css
Labels: 🎨Design
